### ISSUE TITLE
自动化采集的设想

### ISSUE THREAD

**Issue by unusuallman** [JoeanAmier/XHS_Downloader#10]
本地cookie能否成功获取图片与webid和websession相关

只需要可以自动的获取和运行时维护好就可以持续性的获取图片，结束的时候再保存到配置文件中即可

但是自动化采集不能采集搜索出来的web界面，没有有效的abroadID去请求列表元素，获得exporeID

**Comment by unusuallman** [comment]
fork 了一份，亲自上手随便写了写，发现还是有许多问题的（是说我自己）

**Comment by JoeanAmier** [comment]
折腾小红书不仅仅要考虑技术，还需要考虑小红书的法务。

**Comment by unusuallman** [comment]
**也对，不折腾了**
